### ISSUE TITLE
在你使用我相关的代码的时候，请注明原作者，而不是改作者改成你自己，如果不注明，请删除本仓库

### ISSUE THREAD

**Issue by laobie** [myloften/GroupIconSample#1]
Apache Licence 2.0

Apache Licence是著名的非盈利开源组织Apache采用的协议。该协议和BSD类似，同样鼓励代码共享和尊重原作者的著作权，同样允许代码修改，再发布（作为开源或商业软件）。需要满足的条件也和BSD类似：

需要给代码的用户一份Apache Licence
如果你修改了代码，需要在被修改的文件中说明。
在延伸的代码中（修改和有源代码衍生的代码中）需要带有原来代码中的协议，商标，专利声明和其他原来作者规定需要包含的说明。
如果再发布的产品中包含一个Notice文件，则在Notice文件中需要带有Apache Licence。你可以在Notice中增加自己的许可，但不可以表现为对Apache Licence构成更改。

**Comment by myloften** [comment]
@laobie 实在不好意思，参考你的代码获益良多，我已注明，谢谢你的提醒

**Comment by laobie** [comment]
OK，开源协议还是得遵守下的，我关闭 issue 了
